### ISSUE TITLE
PHPUnit 9 compatibility

### ISSUE THREAD

**Issue by meyfa** [meyfa/phpunit-assert-gd#4]
PHPUnit 9 has been released a few months ago. At this time, the dependency constraints in phpunit-assert-gd do not allow it to be used.

**Comment by meyfa** [comment]
Apparently there have been a few schema changes for the PHPUnit 9 release. This is not a problem when using phpunit-assert-gd in other projects, although it does pose questions for how to test the library itself.

Which schema do we use, or do we keep separate configs? Or do we make a v3.0 release which supports just PHPUnit 9? Right now I'm unsure how to proceed.

**Comment by bennothommo** [comment]
@meyfa I'd recommend releasing another major version like I had suggested in the [PHPUnit 8 support PR](https://github.com/meyfa/phpunit-assert-gd/pull/2). At least then it follows PHPUnit's versioning as well, so anytime they release a minor or point release which breaks something, you can do the same.

**Comment by meyfa** [comment]
@bennothommo Seems reasonable. This is what we'll do.

**Comment by meyfa** [comment]
PHPUnit 9 support released as v3.0.0
